// THE ROAD TO DOOM - COMPREHENSIVE DATASET
// Curated MCU & Multiverse filmography with STRICT Doomsday essentials

window.DOOM_DATA = {
  // Config & Constants
  targetReleaseDate: "2026-12-18T00:00:00Z", // Avengers: Doomsday Release Date
  movieTitle: "Avengers: Doomsday",
  directors: ["Anthony Russo", "Joe Russo"],
  writers: ["Stephen McFeely"],
  starringDoom: "Robert Downey Jr. as Victor Von Doom",

  // Master Watchlist Items
  // Note: Only direct Doomsday narrative keystones are marked essential: true.
  items: [
    // --- PHASE 1 ---
    {
      id: "iron-man-2008",
      title: "Iron Man",
      year: 2008,
      releaseDate: "2008-05-02",
      runtime: 126,
      type: "movie",
      universe: "mcu",
      phase: "Phase 1",
      saga: "Infinity Saga",
      storyOrder: 3,
      releaseOrder: 1,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/8ugaeA-nMTc",
      poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
      synopsis: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
      doomConnection: "Introduces Robert Downey Jr. to the MCU. Provides the ultimate emotional background for why Victor Von Doom sharing Tony Stark's face will shock Earth-616 heroes.",
      postCredits: "Nick Fury steps out of the shadows to introduce the 'Avengers Initiative'.",
      keyCharacters: ["Tony Stark", "Pepper Potts", "James Rhodes", "Nick Fury", "Obadiah Stane"],
      incursionRisk: "None"
    },
    {
      id: "the-incredible-hulk-2008",
      title: "The Incredible Hulk",
      year: 2008,
      releaseDate: "2008-06-13",
      runtime: 112,
      type: "movie",
      universe: "mcu",
      phase: "Phase 1",
      saga: "Infinity Saga",
      storyOrder: 5,
      releaseOrder: 2,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/xbqNb2PFKKA",
      poster: "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAi1b0psgpy0b.jpg",
      synopsis: "Scientist Bruce Banner desperately seeks a cure for the gamma radiation that contaminated his cells and turns him into the raging Hulk.",
      doomConnection: "Introduces General Thaddeus 'Thunderbolt' Ross, setting up the presidential storyline leading into Brave New World and Red Hulk.",
      postCredits: "Tony Stark meets General Ross at a bar, teasing the formation of an elite team.",
      keyCharacters: ["Bruce Banner", "Betty Ross", "General Ross", "Emil Blonsky / Abomination", "The Leader"],
      incursionRisk: "None"
    },
    {
      id: "iron-man-2-2010",
      title: "Iron Man 2",
      year: 2010,
      releaseDate: "2010-05-07",
      runtime: 124,
      type: "movie",
      universe: "mcu",
      phase: "Phase 1",
      saga: "Infinity Saga",
      storyOrder: 4,
      releaseOrder: 3,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/wKtcmiifycU",
      poster: "https://image.tmdb.org/t/p/w500/6WBeq4ubcw39Vscj0l59qGImum3.jpg",
      synopsis: "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful madman.",
      doomConnection: "Expands Howard Stark's technological legacy and introduces Natasha Romanoff and War Machine.",
      postCredits: "Agent Coulson discovers Mjolnir in a New Mexico crater.",
      keyCharacters: ["Tony Stark", "Natasha Romanoff", "James Rhodes", "Justin Hammer", "Ivan Vanko"],
      incursionRisk: "None"
    },
    {
      id: "thor-2011",
      title: "Thor",
      year: 2011,
      releaseDate: "2011-05-06",
      runtime: 115,
      type: "movie",
      universe: "mcu",
      phase: "Phase 1",
      saga: "Infinity Saga",
      storyOrder: 6,
      releaseOrder: 4,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/JOddp-nlNvQ",
      poster: "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qx.jpg",
      synopsis: "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard, where he soon becomes one of their finest defenders.",
      doomConnection: "Introduces Asgardian cosmology, Yggdrasil the World Tree (which God Loki later binds), the Tesseract, and Loki.",
      postCredits: "Nick Fury shows Dr. Selvig the Tesseract; Loki influences Selvig through the mirror.",
      keyCharacters: ["Thor", "Loki", "Odin", "Jane Foster", "Heimdall", "Erik Selvig"],
      incursionRisk: "Low"
    },
    {
      id: "captain-america-first-avenger-2011",
      title: "Captain America: The First Avenger",
      year: 2011,
      releaseDate: "2011-07-22",
      runtime: 124,
      type: "movie",
      universe: "mcu",
      phase: "Phase 1",
      saga: "Infinity Saga",
      storyOrder: 1,
      releaseOrder: 5,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/JerVrbLldXw",
      poster: "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpqjqDIFv6.jpg",
      synopsis: "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a 'Super-Soldier serum'.",
      doomConnection: "Origin of Steve Rogers, Bucky Barnes, and the Space Stone / Tesseract.",
      postCredits: "Steve wakes up in modern-day Times Square and Nick Fury approaches him with an assignment.",
      keyCharacters: ["Steve Rogers", "Peggy Carter", "Bucky Barnes", "Red Skull", "Howard Stark"],
      incursionRisk: "Low"
    },
    {
      id: "the-avengers-2012",
      title: "The Avengers",
      year: 2012,
      releaseDate: "2012-05-04",
      runtime: 143,
      type: "movie",
      universe: "mcu",
      phase: "Phase 1",
      saga: "Infinity Saga",
      storyOrder: 7,
      releaseOrder: 6,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/eOrNdBpGMv8",
      poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
      synopsis: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army.",
      doomConnection: "The first Avengers assembly. Introduces the Mind Stone (Scepter), Thanos in post-credits, and 2012 Battle of New York.",
      postCredits: "The Other warns Thanos that to challenge humans is to 'court Death'.",
      keyCharacters: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Loki", "Thanos"],
      incursionRisk: "Moderate"
    },

    // --- PHASE 2 ---
    {
      id: "iron-man-3-2013",
      title: "Iron Man 3",
      year: 2013,
      releaseDate: "2013-05-03",
      runtime: 130,
      type: "movie",
      universe: "mcu",
      phase: "Phase 2",
      saga: "Infinity Saga",
      storyOrder: 8,
      releaseOrder: 7,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/Ke1Y3P9D0Bc",
      poster: "https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXSXV9su9un.jpg",
      synopsis: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
      doomConnection: "Explores Tony Stark's PTSD after New York and automated defense armor.",
      postCredits: "Tony recounts his story to Bruce Banner.",
      keyCharacters: ["Tony Stark", "Pepper Potts", "Aldrich Killian", "Trevor Slattery", "James Rhodes"],
      incursionRisk: "None"
    },
    {
      id: "thor-the-dark-world-2013",
      title: "Thor: The Dark World",
      year: 2013,
      releaseDate: "2013-11-08",
      runtime: 112,
      type: "movie",
      universe: "mcu",
      phase: "Phase 2",
      saga: "Infinity Saga",
      storyOrder: 9,
      releaseOrder: 8,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/npvJ9FTgZbM",
      poster: "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
      synopsis: "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous journey that will reunite him with Jane Foster.",
      doomConnection: "Introduces the Reality Stone (Aether) and the Convergence of Realms.",
      postCredits: "Volstagg and Sif hand the Aether to The Collector for safekeeping.",
      keyCharacters: ["Thor", "Loki", "Jane Foster", "Malekith", "The Collector"],
      incursionRisk: "Moderate"
    },
    {
      id: "captain-america-winter-soldier-2014",
      title: "Captain America: The Winter Soldier",
      year: 2014,
      releaseDate: "2014-04-04",
      runtime: 136,
      type: "movie",
      universe: "mcu",
      phase: "Phase 2",
      saga: "Infinity Saga",
      storyOrder: 10,
      releaseOrder: 9,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/7SlILk2WMTI",
      poster: "https://image.tmdb.org/t/p/w500/tVFRpFw3xTed5fDuWPlHGio2qAG.jpg",
      synopsis: "As Steve Rogers struggles to embrace his role in the modern world, he teams up with Black Widow and Falcon to battle a new menace.",
      doomConnection: "The Russo Brothers' debut MCU film. Introduces Sam Wilson and re-introduces Bucky Barnes.",
      postCredits: "Baron Strucker observes Wanda and Pietro Maximoff in experimental cells.",
      keyCharacters: ["Steve Rogers", "Sam Wilson", "Bucky Barnes", "Natasha Romanoff", "Nick Fury"],
      incursionRisk: "Low"
    },
    {
      id: "guardians-of-the-galaxy-2014",
      title: "Guardians of the Galaxy",
      year: 2014,
      releaseDate: "2014-08-01",
      runtime: 121,
      type: "movie",
      universe: "mcu",
      phase: "Phase 2",
      saga: "Infinity Saga",
      storyOrder: 11,
      releaseOrder: 10,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/d96cjJhvlMA",
      poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
      synopsis: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
      doomConnection: "Cosmic expansion, introduces the Power Stone (Orb) and Celestials lore.",
      postCredits: "The Collector sits in his ruined museum with Cosmo and Howard the Duck.",
      keyCharacters: ["Peter Quill", "Gamora", "Drax", "Rocket", "Groot", "Ronan", "Nebula", "Thanos"],
      incursionRisk: "Low"
    },
    {
      id: "avengers-age-of-ultron-2015",
      title: "Avengers: Age of Ultron",
      year: 2015,
      releaseDate: "2015-05-01",
      runtime: 141,
      type: "movie",
      universe: "mcu",
      phase: "Phase 2",
      saga: "Infinity Saga",
      storyOrder: 13,
      releaseOrder: 11,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/tmeOjFno6Do",
      poster: "https://image.tmdb.org/t/p/w500/4ssDuvEDkS9zb5fCrnvFLqq1pcg.jpg",
      synopsis: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong.",
      doomConnection: "Debuts Wanda Maximoff and Vision. The destruction of Sokovia reshapes Eastern European geopolitics.",
      postCredits: "Thanos retrieves the Infinity Gauntlet.",
      keyCharacters: ["Iron Man", "Captain America", "Thor", "Hulk", "Wanda Maximoff", "Vision", "Ultron"],
      incursionRisk: "Moderate"
    },
    {
      id: "ant-man-2015",
      title: "Ant-Man",
      year: 2015,
      releaseDate: "2015-07-17",
      runtime: 117,
      type: "movie",
      universe: "mcu",
      phase: "Phase 2",
      saga: "Infinity Saga",
      storyOrder: 14,
      releaseOrder: 12,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/pWdKf3MneyI",
      poster: "https://image.tmdb.org/t/p/w500/8SwHuzj2uUqZk1lVb0Yq90f7qI5.jpg",
      synopsis: "Armed with a super-suit with the astonishing ability to shrink in scale, Scott Lang must embrace his inner hero.",
      doomConnection: "Introduces the Quantum Realm.",
      postCredits: "Hank Pym presents Hope with the Wasp suit.",
      keyCharacters: ["Scott Lang", "Hank Pym", "Hope van Dyne", "Darren Cross / Yellowjacket"],
      incursionRisk: "Low"
    },

    // --- PHASE 3 ---
    {
      id: "captain-america-civil-war-2016",
      title: "Captain America: Civil War",
      year: 2016,
      releaseDate: "2016-05-06",
      runtime: 147,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 15,
      releaseOrder: 13,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/dKrVegVI0Us",
      poster: "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
      synopsis: "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
      doomConnection: "Fractures the Avengers; introduces Tom Holland's Spider-Man and Chadwick Boseman's Black Panther.",
      postCredits: "Bucky enters cryogenic sleep in Wakanda; Peter tests new Stark web shooters.",
      keyCharacters: ["Steve Rogers", "Tony Stark", "Natasha Romanoff", "Bucky Barnes", "Sam Wilson", "Spider-Man", "Black Panther"],
      incursionRisk: "Moderate"
    },
    {
      id: "doctor-strange-2016",
      title: "Doctor Strange",
      year: 2016,
      releaseDate: "2016-11-04",
      runtime: 115,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 17,
      releaseOrder: 14,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/HSzx-zryEgM",
      poster: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wMgrghcyx.jpg",
      synopsis: "While on a journey of healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
      doomConnection: "Introduces the Mystic Arts, the Mirror Dimension, the Multiverse concept, and the Time Stone.",
      postCredits: "Strange agrees to help Thor locate Odin in New York; Mordo steals Pangborn's magic.",
      keyCharacters: ["Stephen Strange", "Ancient One", "Wong", "Mordo", "Dormammu"],
      incursionRisk: "High"
    },
    {
      id: "guardians-of-the-galaxy-vol-2-2017",
      title: "Guardians of the Galaxy Vol. 2",
      year: 2017,
      releaseDate: "2017-05-05",
      runtime: 136,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 12,
      releaseOrder: 15,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/dW1BIid8Osg",
      poster: "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9MFbBOKiJduP.jpg",
      synopsis: "The Guardians struggle to keep together while dealing with personal family issues, notably Star-Lord's father Ego.",
      doomConnection: "Introduces Celestials (Ego) and cosmic scaling.",
      postCredits: "Ayesha reveals the creation of Adam Warlock.",
      keyCharacters: ["Peter Quill", "Gamora", "Ego", "Nebula", "Mantis", "Rocket"],
      incursionRisk: "Low"
    },
    {
      id: "spider-man-homecoming-2017",
      title: "Spider-Man: Homecoming",
      year: 2017,
      releaseDate: "2017-07-07",
      runtime: 133,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 16,
      releaseOrder: 16,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/39udgGPyYMg",
      poster: "https://image.tmdb.org/t/p/w500/c24sv2weODPJUUVmsFi4KWhtN32.jpg",
      synopsis: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.",
      doomConnection: "Develops the Tony Stark / Peter Parker mentor relationship.",
      postCredits: "Mac Gargan talks to Adrian Toomes in prison.",
      keyCharacters: ["Peter Parker", "Tony Stark", "Adrian Toomes / Vulture", "Ned Leeds"],
      incursionRisk: "None"
    },
    {
      id: "thor-ragnarok-2017",
      title: "Thor: Ragnarok",
      year: 2017,
      releaseDate: "2017-11-03",
      runtime: 130,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 18,
      releaseOrder: 17,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/ue80QwXMRHg",
      poster: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
      synopsis: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarok, the destruction of his world.",
      doomConnection: "Destruction of Asgard, Thor and Loki's reconciliation, and prelude to Infinity War.",
      postCredits: "The Statesman ship is intercepted by Thanos's dreadnought Sanctuary II.",
      keyCharacters: ["Thor", "Loki", "Hulk", "Hela", "Valkyrie", "Grandmaster"],
      incursionRisk: "Moderate"
    },
    {
      id: "black-panther-2018",
      title: "Black Panther",
      year: 2018,
      releaseDate: "2018-02-16",
      runtime: 134,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 19,
      releaseOrder: 18,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/xjDjIWPwcPU",
      poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
      synopsis: "T'Challa, heir to the hidden kingdom of Wakanda, must step forward to lead his people into a new future.",
      doomConnection: "Introduces Wakanda and Vibranium technology.",
      postCredits: "T'Challa opens Wakanda to the UN; Bucky wakes as the White Wolf.",
      keyCharacters: ["T'Challa", "Killmonger", "Shuri", "Okoye", "M'Baku"],
      incursionRisk: "Low"
    },
    {
      id: "avengers-infinity-war-2018",
      title: "Avengers: Infinity War",
      year: 2018,
      releaseDate: "2018-04-27",
      runtime: 149,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 20,
      releaseOrder: 19,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/6ZfuNTqbHE8",
      poster: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      synopsis: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his devastation puts an end to the universe.",
      doomConnection: "CRITICAL ESSENTIAL. Directed by the Russo Brothers. Cosmic stakes, Doctor Strange viewing 14,000,605 timelines, and the catastrophic Snap.",
      postCredits: "Nick Fury pages Captain Marvel moments before turning to dust.",
      keyCharacters: ["Thanos", "Iron Man", "Thor", "Captain America", "Doctor Strange", "Spider-Man", "Scarlet Witch"],
      incursionRisk: "Critical"
    },
    {
      id: "ant-man-and-the-wasp-2018",
      title: "Ant-Man and the Wasp",
      year: 2018,
      releaseDate: "2018-07-06",
      runtime: 118,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 21,
      releaseOrder: 20,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/8_rTIAOohas",
      poster: "https://image.tmdb.org/t/p/w500/e90v2J1959QPVXuDA1wf42795x1.jpg",
      synopsis: "As Scott Lang balances being both a superhero and a father, Hope and Dr. Hank Pym present an urgent mission into the Quantum Realm.",
      doomConnection: "Introduces Ava Starr (Ghost), who joins the Thunderbolts*.",
      postCredits: "Hank, Janet, and Hope turn to dust while Scott is stranded in the Quantum Realm.",
      keyCharacters: ["Scott Lang", "Hope van Dyne", "Hank Pym", "Ava Starr / Ghost"],
      incursionRisk: "Low"
    },
    {
      id: "captain-marvel-2019",
      title: "Captain Marvel",
      year: 2019,
      releaseDate: "2019-03-08",
      runtime: 124,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 2,
      releaseOrder: 21,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/Z1BCujX3pw8",
      poster: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7Txi.jpg",
      synopsis: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in a galactic war between two alien races.",
      doomConnection: "Origin of Carol Danvers and the Tesseract in the 1990s.",
      postCredits: "Carol arrives at the Avengers compound responding to the pager.",
      keyCharacters: ["Carol Danvers", "Nick Fury", "Talos", "Maria Rambeau"],
      incursionRisk: "Low"
    },
    {
      id: "avengers-endgame-2019",
      title: "Avengers: Endgame",
      year: 2019,
      releaseDate: "2019-04-26",
      runtime: 181,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 22,
      releaseOrder: 22,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/TcMBFSGVi1c",
      poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      synopsis: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
      doomConnection: "CRITICAL ESSENTIAL. Tony Stark's sacrifice ('I am Iron Man'), Steve passing the shield to Sam Wilson, and 2012 Loki escaping with the Tesseract — which directly births the Multiverse timeline branches!",
      postCredits: "Sound of Tony Stark forging his Mark I armor echoes over the Marvel Studios logo.",
      keyCharacters: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Thanos", "Loki"],
      incursionRisk: "Critical"
    },
    {
      id: "spider-man-far-from-home-2019",
      title: "Spider-Man: Far From Home",
      year: 2019,
      releaseDate: "2019-07-02",
      runtime: 129,
      type: "movie",
      universe: "mcu",
      phase: "Phase 3",
      saga: "Infinity Saga",
      storyOrder: 24,
      releaseOrder: 23,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/Nt9L1jCKGnE",
      poster: "https://image.tmdb.org/t/p/w500/4q2hz2mYflg7P4mSl8afSuPBHGd.jpg",
      synopsis: "Following the events of Avengers: Endgame, Spider-Man must step up to take on new threats in a world that has changed forever.",
      doomConnection: "Deals with the loss of Tony Stark; Peter's identity is exposed.",
      postCredits: "J. Jonah Jameson broadcasts Mysterio's doctored footage, unmasking Peter Parker.",
      keyCharacters: ["Peter Parker", "Quentin Beck / Mysterio", "MJ", "Ned Leeds"],
      incursionRisk: "Low"
    },

    // --- PHASE 4 ---
    {
      id: "wandavision-2021",
      title: "WandaVision (Season 1)",
      year: 2021,
      releaseDate: "2021-01-15",
      runtime: 350,
      type: "series",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 23,
      releaseOrder: 24,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/UBhlqe2KVt4",
      poster: "https://image.tmdb.org/t/p/w500/glKDHgvgNPcy94IR51Wcfhdvmqb.jpg",
      synopsis: "Living idealized suburban lives, super-powered beings Wanda and Vision begin to suspect that everything is not as it seems.",
      doomConnection: "Wanda embraces her destiny as the Scarlet Witch and discovers the Darkhold, leading into Multiverse of Madness.",
      postCredits: "Wanda astral-projects while reading the Darkhold, hearing her children across the multiverse.",
      keyCharacters: ["Wanda Maximoff", "Vision", "Agatha Harkness", "Monica Rambeau", "Billy & Tommy"],
      incursionRisk: "High"
    },
    {
      id: "the-falcon-and-the-winter-soldier-2021",
      title: "The Falcon and the Winter Soldier",
      year: 2021,
      releaseDate: "2021-03-19",
      runtime: 300,
      type: "series",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 25,
      releaseOrder: 25,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/IWBsDaFWyTE",
      poster: "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
      synopsis: "Sam Wilson and Bucky Barnes team up in a global adventure that tests their abilities and their patience.",
      doomConnection: "Sam Wilson becomes Captain America; introduces John Walker and Valentina.",
      postCredits: "Sharon Carter receives a full pardon and prepares to sell government secrets.",
      keyCharacters: ["Sam Wilson", "Bucky Barnes", "John Walker", "Valentina", "Baron Zemo"],
      incursionRisk: "Low"
    },
    {
      id: "loki-season-1-2021",
      title: "Loki (Season 1)",
      year: 2021,
      releaseDate: "2021-06-09",
      runtime: 285,
      type: "series",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 26,
      releaseOrder: 26,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/nW948Va-l10",
      poster: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc39gTu0j2j0P0neZvi.jpg",
      synopsis: "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.",
      doomConnection: "CRITICAL ESSENTIAL. Introduces the Time Variance Authority (TVA), the Sacred Timeline, timeline branching, Sylvie, and the Citadel at the End of Time. The death of He Who Remains unleashes the Multiverse.",
      postCredits: "A stamp confirms: 'Loki will return in Season 2.'",
      keyCharacters: ["Loki", "Mobius M. Mobius", "Sylvie", "Ravonna Renslayer", "He Who Remains"],
      incursionRisk: "Critical"
    },
    {
      id: "black-widow-2021",
      title: "Black Widow",
      year: 2021,
      releaseDate: "2021-07-09",
      runtime: 134,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 15.5,
      releaseOrder: 27,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/ybji16u608U",
      poster: "https://image.tmdb.org/t/p/w500/qAZ0wfFTwnr9uo2CrTQY8Ah1NdQ.jpg",
      synopsis: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
      doomConnection: "Introduces Yelena Belova, Alexei Shostakov (Red Guardian), and Taskmaster.",
      postCredits: "Valentina assigns Yelena to target Clint Barton.",
      keyCharacters: ["Natasha Romanoff", "Yelena Belova", "Alexei Shostakov", "Valentina"],
      incursionRisk: "None"
    },
    {
      id: "what-if-season-1-2021",
      title: "What If...? (Season 1)",
      year: 2021,
      releaseDate: "2021-08-11",
      runtime: 270,
      type: "series",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 27,
      releaseOrder: 28,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/x9D0uUKJ5KI",
      poster: "https://image.tmdb.org/t/p/w500/lztvEP6aq7nCwh961v6nflmE19U.jpg",
      synopsis: "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head.",
      doomConnection: "Introduces The Watcher, Captain Carter, Strange Supreme, and multiversal collapse concepts.",
      postCredits: "Captain Carter discovers the Hydra Stomper armor containing Steve Rogers alive.",
      keyCharacters: ["The Watcher", "Captain Carter", "Strange Supreme", "Infinity Ultron"],
      incursionRisk: "Critical"
    },
    {
      id: "shang-chi-2021",
      title: "Shang-Chi and the Legend of the Ten Rings",
      year: 2021,
      releaseDate: "2021-09-03",
      runtime: 132,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 28,
      releaseOrder: 29,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/8YjFbMbfXaQ",
      poster: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjd2xA4JJ4JkWk8koPn.jpg",
      synopsis: "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
      doomConnection: "Introduces the Ten Rings transmitting a cosmic beacon across dimensions.",
      postCredits: "Wong, Bruce Banner, and Carol Danvers analyze the Rings.",
      keyCharacters: ["Shang-Chi", "Wenwu / The Mandarin", "Xialing", "Katy", "Wong"],
      incursionRisk: "Moderate"
    },
    {
      id: "eternals-2021",
      title: "Eternals",
      year: 2021,
      releaseDate: "2021-11-05",
      runtime: 156,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 29,
      releaseOrder: 30,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/0WVOK305NXU",
      poster: "https://image.tmdb.org/t/p/w500/b6q0TXcq2F74NDEZ24qog4g66hm.jpg",
      synopsis: "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
      doomConnection: "Celestial Tiamut emerges in the ocean, becoming the Adamantium Island fought over in Brave New World.",
      postCredits: "Starfox (Eros) teleports aboard the Domo; Blade warns Dane Whitman.",
      keyCharacters: ["Sersi", "Ikaris", "Thena", "Kingk", "Arishem", "Eros / Starfox"],
      incursionRisk: "Moderate"
    },
    {
      id: "spider-man-no-way-home-2021",
      title: "Spider-Man: No Way Home",
      year: 2021,
      releaseDate: "2021-12-17",
      runtime: 148,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 30,
      releaseOrder: 31,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/JfVOs4VSpmA",
      poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      synopsis: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds appear.",
      doomConnection: "CRITICAL ESSENTIAL. The multiverse tears wide open, pulling Tobey Maguire, Andrew Garfield, and outside villains into Earth-616. The foundation of the Multiverse crossover era.",
      postCredits: "Venom leaves a symbiote drop in a Mexican bar.",
      keyCharacters: ["Peter Parker (MCU)", "Peter Parker (Raimi)", "Peter Parker (TASM)", "Doctor Strange", "Green Goblin", "Doc Ock"],
      incursionRisk: "Critical"
    },
    {
      id: "doctor-strange-multiverse-madness-2022",
      title: "Doctor Strange in the Multiverse of Madness",
      year: 2022,
      releaseDate: "2022-05-06",
      runtime: 126,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 31,
      releaseOrder: 32,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/aWzlQ2N6vxg",
      poster: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
      synopsis: "Doctor Strange teams up with America Chavez to traverse the multiverse while evading a corrupted Scarlet Witch.",
      doomConnection: "THE DIRECT DEFINITION OF INCURSIONS. Introduces the concept of universes colliding and annihilating each other. Debuts the Illuminati with Reed Richards (John Krasinski) and Professor X (Patrick Stewart). Clea recruits Strange to stop an incoming incursion.",
      postCredits: "Clea opens a portal to the Dark Dimension to fix an incursion caused by Strange.",
      keyCharacters: ["Doctor Strange", "Scarlet Witch", "America Chavez", "Reed Richards", "Charles Xavier", "Clea"],
      incursionRisk: "Catastrophic"
    },
    {
      id: "thor-love-and-thunder-2022",
      title: "Thor: Love and Thunder",
      year: 2022,
      releaseDate: "2022-07-08",
      runtime: 119,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 32,
      releaseOrder: 33,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/Go8nTmfrQd8",
      poster: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4F0b69em299EGq39j.jpg",
      synopsis: "Thor enlists the help of Valkyrie, Korg and Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
      doomConnection: "Introduces Eternity at the center of the universe.",
      postCredits: "Zeus sends Hercules to hunt Thor; Jane arrives in Valhalla.",
      keyCharacters: ["Thor", "Jane Foster / Mighty Thor", "Gorr the God Butcher", "Valkyrie"],
      incursionRisk: "Low"
    },
    {
      id: "black-panther-wakanda-forever-2022",
      title: "Black Panther: Wakanda Forever",
      year: 2022,
      releaseDate: "2022-11-11",
      runtime: 161,
      type: "movie",
      universe: "mcu",
      phase: "Phase 4",
      saga: "Multiverse Saga",
      storyOrder: 33,
      releaseOrder: 34,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/_Z3QKkl1WyM",
      poster: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
      synopsis: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
      doomConnection: "Introduces Namor and the underwater kingdom of Talokan, Riri Williams, and Shuri as Black Panther.",
      postCredits: "Nakia introduces Shuri to Prince T'Challa (Toussiant).",
      keyCharacters: ["Shuri", "Namor", "Queen Ramonda", "Okoye", "Riri Williams", "M'Baku"],
      incursionRisk: "Low"
    },

    // --- PHASE 5 ---
    {
      id: "ant-man-quantumania-2023",
      title: "Ant-Man and the Wasp: Quantumania",
      year: 2023,
      releaseDate: "2023-02-17",
      runtime: 124,
      type: "movie",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 34,
      releaseOrder: 35,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/ZlNFpri-Y40",
      poster: "https://image.tmdb.org/t/p/w500/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
      synopsis: "Scott Lang and Hope van Dyne explore the Quantum Realm and interact with strange creatures outside space and time.",
      doomConnection: "Shows the sub-atomic Quantum Realm beyond standard space-time.",
      postCredits: "The Council of Kangs convenes; Loki and Mobius locate Victor Timely.",
      keyCharacters: ["Scott Lang", "Hope van Dyne", "Kang the Conqueror", "Janet van Dyne"],
      incursionRisk: "High"
    },
    {
      id: "guardians-of-the-galaxy-vol-3-2023",
      title: "Guardians of the Galaxy Vol. 3",
      year: 2023,
      releaseDate: "2023-05-05",
      runtime: 150,
      type: "movie",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 35,
      releaseOrder: 36,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/u3V5KDHRQvk",
      poster: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg",
      synopsis: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and save Rocket.",
      doomConnection: "Star-Lord returns to Earth, setting him up for future Earth-based Avengers crossovers.",
      postCredits: "The new Guardians team takes on a mission; Peter eats breakfast with his grandfather on Earth.",
      keyCharacters: ["Rocket", "Peter Quill", "Gamora", "Nebula", "Drax", "Mantis"],
      incursionRisk: "None"
    },
    {
      id: "loki-season-2-2023",
      title: "Loki (Season 2)",
      year: 2023,
      releaseDate: "2023-10-04",
      runtime: 290,
      type: "series",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 36,
      releaseOrder: 37,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/dug56u8NNBn",
      poster: "https://image.tmdb.org/t/p/w500/voHUmluYmKyleFk9a3Y2YrMo7y5.jpg",
      synopsis: "Loki navigates an ever-expanding multiverse in search of Sylvie, Miss Minutes and the truth of free will.",
      doomConnection: "THE NARRATIVE CORNERSTONE OF THE MULTIVERSE SAGA. Loki destroys the Loom, weaves all dying timeline branches with his bare hands, and ascends the throne of Yggdrasil as the GOD OF STORIES. He is physically holding the entire multiverse together until Doom strikes.",
      postCredits: "Loki sits alone at the throne of Yggdrasil holding infinite realities.",
      keyCharacters: ["Loki (God of Stories)", "Mobius", "Sylvie", "Ouroboros (O.B.)", "Victor Timely"],
      incursionRisk: "Critical"
    },
    {
      id: "the-marvels-2023",
      title: "The Marvels",
      year: 2023,
      releaseDate: "2023-11-10",
      runtime: 105,
      type: "movie",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 37,
      releaseOrder: 38,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/wS_qbD02650",
      poster: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w0bUMMTps5.jpg",
      synopsis: "Carol Danvers, Kamala Khan, and Monica Rambeau begin swapping places every time they use their powers.",
      doomConnection: "Monica Rambeau is trapped across an incursion rift in the Fox X-Men alternate universe with Kelsey Grammer's Beast.",
      postCredits: "Beast checks Monica's vitals inside the X-Mansion medical bay beneath the X-Men seal.",
      keyCharacters: ["Carol Danvers", "Monica Rambeau", "Kamala Khan", "Beast (Hank McCoy)"],
      incursionRisk: "Critical"
    },
    {
      id: "deadpool-and-wolverine-2024",
      title: "Deadpool & Wolverine",
      year: 2024,
      releaseDate: "2024-07-26",
      runtime: 128,
      type: "movie",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 38,
      releaseOrder: 39,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/73_1biulkYk",
      poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      synopsis: "A listless Wade Wilson must reluctantly team up with a cynical Wolverine to save his homeworld from TVA destruction.",
      doomConnection: "CRITICAL ESSENTIAL. Direct cinematic bridge between Marvel Studios, the TVA, and Fox's Earth-10005. Features The Void (the desolate wasteland of pruned universes — the architectural precursor to Battleworld).",
      postCredits: "Deadpool plays TVA security footage proving Johnny Storm's rant.",
      keyCharacters: ["Deadpool (Wade Wilson)", "Wolverine (Logan)", "Cassandra Nova", "Mr. Paradox", "Gambit", "Blade", "X-23"],
      incursionRisk: "Critical"
    },
    {
      id: "agatha-all-along-2024",
      title: "Agatha All Along",
      year: 2024,
      releaseDate: "2024-09-18",
      runtime: 360,
      type: "series",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 39,
      releaseOrder: 40,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/R9pXbFZ1E2U",
      poster: "https://image.tmdb.org/t/p/w500/mCR2Zq4aWfE31GjLh6P7d8i7V7a.jpg",
      synopsis: "A spellbound Agatha Harkness regains freedom thanks to a cynical teen who helps her form a coven to walk the legendary Witches' Road.",
      doomConnection: "Confirms Teen as Billy Maximoff (Wiccan) and establishes magic multiversal rules.",
      postCredits: "Ghost Agatha and Billy set out to locate Tommy Maximoff's reincarnated soul.",
      keyCharacters: ["Agatha Harkness", "Billy Maximoff (Wiccan)", "Rio Vidal (Death)"],
      incursionRisk: "Moderate"
    },
    {
      id: "captain-america-brave-new-world-2025",
      title: "Captain America: Brave New World",
      year: 2025,
      releaseDate: "2025-02-14",
      runtime: 118,
      type: "movie",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 40,
      releaseOrder: 41,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/1pHDWnXmKMY",
      poster: "https://image.tmdb.org/t/p/w500/pzIddQemrWz2qkW11L8Z96v9wO3.jpg",
      synopsis: "Sam Wilson finds himself in the middle of an international incident after meeting with newly elected U.S. President Thaddeus Ross.",
      doomConnection: "CRITICAL ESSENTIAL. Sam Wilson leads Earth's defense; President Thaddeus Ross transforms into Red Hulk; global war for Adamantium harvested from Celestial Tiamut destabilizes Earth for Doom's arrival.",
      postCredits: "Sets up the global state leading directly into Thunderbolts* and Avengers: Doomsday.",
      keyCharacters: ["Sam Wilson (Captain America)", "President Ross / Red Hulk", "Joaquin Torres (Falcon)", "Isaiah Bradley", "The Leader"],
      incursionRisk: "High"
    },
    {
      id: "thunderbolts-2025",
      title: "Thunderbolts*",
      year: 2025,
      releaseDate: "2025-05-02",
      runtime: 126,
      type: "movie",
      universe: "mcu",
      phase: "Phase 5",
      saga: "Multiverse Saga",
      storyOrder: 41,
      releaseOrder: 42,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/v-bHwtB8t_A",
      poster: "https://image.tmdb.org/t/p/w500/mKsm9f1f0aKkS54G0R1G5aB0k1.jpg",
      synopsis: "An irreverent team of anti-heroes and reformed villains are sent on covert government missions under Valentina Allegra de Fontaine.",
      doomConnection: "CRITICAL ESSENTIAL PRELUDE. Yelena Belova, Bucky Barnes, Red Guardian, and U.S. Agent encounter 'Bob' (Robert Reynolds / The Sentry) — an omega-level cosmic powerhouse who plays a pivotal role in the coming crisis.",
      postCredits: "The team is mobilized as the frontline defense against approaching multiversal anomalies.",
      keyCharacters: ["Yelena Belova", "Bucky Barnes", "Alexei Shostakov", "Ava Starr / Ghost", "John Walker", "Bob Reynolds (Sentry)", "Valentina"],
      incursionRisk: "High"
    },

    // --- PHASE 6 ---
    {
      id: "fantastic-four-first-steps-2025",
      title: "The Fantastic Four: First Steps",
      year: 2025,
      releaseDate: "2025-07-25",
      runtime: 125,
      type: "movie",
      universe: "mcu",
      phase: "Phase 6",
      saga: "Multiverse Saga",
      storyOrder: 42,
      releaseOrder: 43,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/7V3y2kPzY6o",
      poster: "https://image.tmdb.org/t/p/w500/6A774s1E9N9J9sK9jN2V8A8W5m1.jpg",
      synopsis: "Set in a 1960s retro-futuristic world, Marvel's First Family must balance family with heroism when Silver Surfer and Galactus arrive.",
      doomConnection: "THE DIRECT ORIGIN OF VICTOR VON DOOM & REED RICHARDS. Sets up the retro-future universe's imminent incursion collapse, forcing the Fantastic Four and Doctor Doom into Earth-616.",
      postCredits: "Teases Robert Downey Jr.'s Victor Von Doom preparing for Doomsday.",
      keyCharacters: ["Reed Richards (Pedro Pascal)", "Sue Storm", "Johnny Storm", "Ben Grimm", "Galactus", "Victor Von Doom"],
      incursionRisk: "Catastrophic"
    },
    {
      id: "spider-man-brand-new-day-2026",
      title: "Spider-Man 4: Brand New Day",
      year: 2026,
      releaseDate: "2026-07-31",
      runtime: 135,
      type: "movie",
      universe: "mcu",
      phase: "Phase 6",
      saga: "Multiverse Saga",
      storyOrder: 43,
      releaseOrder: 44,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/JfVOs4VSpmA",
      poster: "https://image.tmdb.org/t/p/w500/4q2hz2mYflg7P4mSl8afSuPBHGd.jpg",
      synopsis: "Peter Parker navigates life as a forgotten street-level hero in New York as dimensional anomalies bleed into Manhattan.",
      doomConnection: "Peter's street-level perspective right before the multiversal incursion strikes New York.",
      postCredits: "Dimensional tears manifest over Manhattan.",
      keyCharacters: ["Peter Parker", "Daredevil", "Ned Leeds", "MJ"],
      incursionRisk: "Critical"
    },
    {
      id: "avengers-doomsday-2026",
      title: "Avengers: Doomsday",
      year: 2026,
      releaseDate: "2026-12-18",
      runtime: 165,
      type: "movie",
      universe: "mcu",
      phase: "Phase 6",
      saga: "Multiverse Saga",
      storyOrder: 44,
      releaseOrder: 45,
      essential: true,
      trailerUrl: "https://www.youtube.com/embed/-JrbS8ZpTFQ",
      poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
      synopsis: "The culmination of the Multiverse Saga. Earth's mightiest heroes, the Fantastic Four, Thunderbolts, and X-Men face Victor Von Doom as incursions threaten to wipe out all reality.",
      doomConnection: "THE DESTINATION. Victor Von Doom harnesses colliding universes to build Battleworld for Secret Wars.",
      postCredits: "The Final Incursion strikes, forging Battleworld.",
      keyCharacters: ["Victor Von Doom (Robert Downey Jr.)", "Reed Richards", "Sam Wilson", "Thor", "Doctor Strange", "Spider-Man", "Loki", "Sentry", "Yelena"],
      incursionRisk: "Universal Collapse / Battleworld"
    },

    // --- FOX X-MEN (OPTIONAL LEGACY) ---
    {
      id: "x-men-2000",
      title: "X-Men",
      year: 2000,
      releaseDate: "2000-07-14",
      runtime: 104,
      type: "movie",
      universe: "xmen",
      phase: "Fox Legacy",
      saga: "Mutant Saga",
      storyOrder: 100,
      releaseOrder: 0.1,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/nbNCkkvP1iQ",
      poster: "https://image.tmdb.org/t/p/w500/bRDAc4GogS9CRRA64cuSZJ1utqd.jpg",
      synopsis: "Two mutant factions led by Xavier and Magneto clash over how to live alongside humanity.",
      doomConnection: "Origin of Hugh Jackman's Wolverine and Patrick Stewart's Charles Xavier (Earth-10005).",
      postCredits: "None",
      keyCharacters: ["Wolverine", "Professor Charles Xavier", "Magneto", "Cyclops", "Jean Grey"],
      incursionRisk: "Multiverse Anchor"
    },
    {
      id: "x2-x-men-united-2003",
      title: "X2: X-Men United",
      year: 2003,
      releaseDate: "2003-05-02",
      runtime: 134,
      type: "movie",
      universe: "xmen",
      phase: "Fox Legacy",
      saga: "Mutant Saga",
      storyOrder: 101,
      releaseOrder: 0.2,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/L1ZzZ3eJ6e0",
      poster: "https://image.tmdb.org/t/p/w500/3o9ZqY2E52sU0K1L5J95P7a6Z4X.jpg",
      synopsis: "The X-Men band together with Magneto to fight Stryker, who seeks to eradicate all mutants.",
      doomConnection: "Deepens Xavier and Magneto's relationship.",
      postCredits: "None",
      keyCharacters: ["Wolverine", "Professor X", "Magneto", "Nightcrawler", "Jean Grey"],
      incursionRisk: "Multiverse Anchor"
    },
    {
      id: "x-men-days-of-future-past-2014",
      title: "X-Men: Days of Future Past",
      year: 2014,
      releaseDate: "2014-05-23",
      runtime: 131,
      type: "movie",
      universe: "xmen",
      phase: "Fox Legacy",
      saga: "Mutant Saga",
      storyOrder: 102,
      releaseOrder: 0.3,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/pK2zYHWDZKo",
      poster: "https://image.tmdb.org/t/p/w500/tK0mP0aL0sE31b8q6f7N8B6Z7K.jpg",
      synopsis: "The X-Men send Wolverine to the past in a desperate effort to prevent doom for mutants.",
      doomConnection: "Timeline-rewriting mutant classic uniting classic and prequel casts.",
      postCredits: "En Sabah Nur (Apocalypse) builds pyramids telekinetically.",
      keyCharacters: ["Wolverine", "Charles Xavier", "Magneto", "Mystique", "Quicksilver"],
      incursionRisk: "High"
    },
    {
      id: "logan-2017",
      title: "Logan",
      year: 2017,
      releaseDate: "2017-03-03",
      runtime: 137,
      type: "movie",
      universe: "xmen",
      phase: "Fox Legacy",
      saga: "Mutant Saga",
      storyOrder: 103,
      releaseOrder: 0.4,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/Div0iP65aZo",
      poster: "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
      synopsis: "A weary Logan cares for an ailing Professor X on the Mexican border until young Laura arrives.",
      doomConnection: "Introduced Laura (X-23) and defined Logan's death as the Anchor Being event that destabilized Earth-10005.",
      postCredits: "None",
      keyCharacters: ["Logan / Wolverine", "Charles Xavier", "Laura / X-23"],
      incursionRisk: "Anchor Collapse"
    },

    // --- SONY SPIDER-MAN (OPTIONAL LEGACY) ---
    {
      id: "spider-man-2002",
      title: "Spider-Man",
      year: 2002,
      releaseDate: "2002-05-03",
      runtime: 121,
      type: "movie",
      universe: "sony",
      phase: "Raimi Legacy",
      saga: "Spider-Verse",
      storyOrder: 200,
      releaseOrder: 0.05,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/t06RUxPbp_c",
      poster: "https://image.tmdb.org/t/p/w500/gh4c2ubiUzBgTV7Umhsd9T4VIY.jpg",
      synopsis: "After being bitten by a genetically-modified spider, Peter Parker becomes Spider-Man.",
      doomConnection: "Tobey Maguire's original universe and origin of Green Goblin.",
      postCredits: "None",
      keyCharacters: ["Peter Parker (Tobey Maguire)", "Norman Osborn", "Mary Jane Watson"],
      incursionRisk: "Low"
    },
    {
      id: "spider-man-2-2004",
      title: "Spider-Man 2",
      year: 2004,
      releaseDate: "2004-06-30",
      runtime: 127,
      type: "movie",
      universe: "sony",
      phase: "Raimi Legacy",
      saga: "Spider-Verse",
      storyOrder: 201,
      releaseOrder: 0.06,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/1s9Yln0Yscw",
      poster: "https://image.tmdb.org/t/p/w500/olxpyq94zl2TaImTlmQCvYvhIOH.jpg",
      synopsis: "Peter Parker battles Doctor Otto Octavius.",
      doomConnection: "Alfred Molina's Doc Ock origin.",
      postCredits: "None",
      keyCharacters: ["Peter Parker", "Otto Octavius / Doc Ock"],
      incursionRisk: "Low"
    },
    {
      id: "the-amazing-spider-man-2012",
      title: "The Amazing Spider-Man",
      year: 2012,
      releaseDate: "2012-07-03",
      runtime: 136,
      type: "movie",
      universe: "sony",
      phase: "Webb Legacy",
      saga: "Spider-Verse",
      storyOrder: 202,
      releaseOrder: 0.07,
      essential: false,
      trailerUrl: "https://www.youtube.com/embed/-tnxzJti6Zo",
      poster: "https://image.tmdb.org/t/p/w500/jIfkxt5FS4rA7NXwEvNdrg5bsb3.jpg",
      synopsis: "Peter Parker gains spider powers and battles The Lizard.",
      doomConnection: "Andrew Garfield's Spider-Man universe.",
      postCredits: "The Man in the Shadows visits Curt Connors.",
      keyCharacters: ["Peter Parker (Andrew Garfield)", "Gwen Stacy", "The Lizard"],
      incursionRisk: "Low"
    }
  ],

  // Marvel's Curated Short Road to Doom (The 10 Pure Doomsday Narrative Milestones)
  shortRoadIds: [
    "avengers-infinity-war-2018",
    "avengers-endgame-2019",
    "loki-season-1-2021",
    "loki-season-2-2023",
    "spider-man-no-way-home-2021",
    "doctor-strange-multiverse-madness-2022",
    "deadpool-and-wolverine-2024",
    "captain-america-brave-new-world-2025",
    "thunderbolts-2025",
    "fantastic-four-first-steps-2025"
  ],

  // Multiverse Character Dossiers
  characters: [
    {
      id: "doctor-doom",
      name: "Victor Von Doom (Doctor Doom)",
      actor: "Robert Downey Jr.",
      universe: "Fantastic Four Retro-Future / Latveria",
      affiliation: "Monarch of Latveria / Sovereign of Battleworld",
      status: "Approaching Earth-616",
      avatar: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Monarch of Latveria, supreme master of both advanced scientific engineering and ancient dark sorcery. In Jonathan Hickman's 2015 Secret Wars, Doom harnessed the power of the Molecule Man and the Beyonders to save the remnants of colliding realities, fashioning himself into 'God Emperor Doom' on Battleworld.",
      mcuRole: "Portrayed by Robert Downey Jr., Doom returns to right what he perceives went wrong in his home universe. Believing Earth-616 heroes live 'stolen lives', he harnesses multiversal incursions to reshape reality under his supreme rule.",
      threatLevel: "Omega / God Tier",
      essentialAppearances: ["The Fantastic Four: First Steps", "Avengers: Doomsday", "Avengers: Secret Wars"]
    },
    {
      id: "reed-richards",
      name: "Reed Richards (Mister Fantastic)",
      actor: "Pedro Pascal",
      universe: "Fantastic Four Retro-Future Universe",
      affiliation: "Fantastic Four / The Council of Reeds",
      status: "Universe in Incursion Peril",
      avatar: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150&auto=format&fit=crop&q=80",
      comicHistory: "The smartest human in the multiverse. Reed's intellectual rivalry with Victor Von Doom spans decades. In the 2015 Secret Wars, Reed created the 'Life Raft' to survive the final incursion and ultimately confronted God Emperor Doom to rebuild the multiverse.",
      mcuRole: "Leader of the Fantastic Four, navigating their retro-future Earth as cosmic incursions threaten extinction, forcing an inter-dimensional migration to Earth-616.",
      threatLevel: "Omega Intelligence",
      essentialAppearances: ["The Fantastic Four: First Steps", "Avengers: Doomsday", "Avengers: Secret Wars"]
    },
    {
      id: "loki-god-of-stories",
      name: "Loki (God of Stories)",
      actor: "Tom Hiddleston",
      universe: "End of Time / Yggdrasil Nexus",
      affiliation: "TVA / Multi-Timeline Guardian",
      status: "Holding the Multiverse Together",
      avatar: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Evolved from God of Mischief into the God of Stories, who wields narrative reality itself to preserve timelines against universal erasure.",
      mcuRole: "Sacrificed personal freedom to replace the Multiversal Loom, physically holding countless timeline branches together with his magic. Sits at the throne of Yggdrasil. The linchpin preventing immediate total collapse.",
      threatLevel: "Multiversal Anchor / God",
      essentialAppearances: ["The Avengers", "Thor: Ragnarok", "Avengers: Infinity War", "Loki Season 1", "Loki Season 2"]
    },
    {
      id: "doctor-strange",
      name: "Stephen Strange (Doctor Strange)",
      actor: "Benedict Cumberbatch",
      universe: "Earth-616",
      affiliation: "Masters of the Mystic Arts",
      status: "In Dark Dimension with Clea fixing Incursions",
      avatar: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Former Sorcerer Supreme who served as God Emperor Doom's sheriff and high priest on Battleworld before aiding the rebellion.",
      mcuRole: "Triggered multiversal incursions through dreamwalking and Darkhold usage; currently traversing dimensions alongside Clea to avert catastrophic reality collisions.",
      threatLevel: "Alpha Sorcerer",
      essentialAppearances: ["Doctor Strange", "Avengers: Infinity War", "Spider-Man: No Way Home", "Doctor Strange in the Multiverse of Madness"]
    },
    {
      id: "spider-man",
      name: "Peter Parker (Spider-Man)",
      actor: "Tom Holland",
      universe: "Earth-616",
      affiliation: "Avengers / Street Level",
      status: "Active in NYC (World forgot his civilian identity)",
      avatar: "https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Moral center of Marvel Comics and key survivor of the 2015 incursion aboard the Life Raft.",
      mcuRole: "Having sacrificed his identity to heal the multiverse in No Way Home, Peter faces the ultimate emotional shock: facing Victor Von Doom, who bears the exact likeness of his beloved mentor, Tony Stark.",
      threatLevel: "Heroic Vanguard",
      essentialAppearances: ["Captain America: Civil War", "Spider-Man: Homecoming", "Avengers: Infinity War", "Avengers: Endgame", "Spider-Man: No Way Home", "Spider-Man 4"]
    },
    {
      id: "captain-america-sam-wilson",
      name: "Sam Wilson (Captain America)",
      actor: "Anthony Mackie",
      universe: "Earth-616",
      affiliation: "Avengers Leader",
      status: "Assembling New Avengers Team",
      avatar: "https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Took up the shield with vibranium wings and led the Avengers through major geopolitical crises.",
      mcuRole: "Official leader of Earth's defense and the Avengers, having faced the Red Hulk and international Adamantium conspiracy in Brave New World.",
      threatLevel: "Tactical Leader",
      essentialAppearances: ["Captain America: The Winter Soldier", "Captain America: Civil War", "Avengers: Endgame", "The Falcon and the Winter Soldier", "Captain America: Brave New World"]
    },
    {
      id: "sentry",
      name: "Robert Reynolds (The Sentry)",
      actor: "Lewis Pullman",
      universe: "Earth-616",
      affiliation: "Thunderbolts*",
      status: "Awakened Power of a Million Exploding Suns",
      avatar: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=150&auto=format&fit=crop&q=80",
      comicHistory: "One of the most powerful and unstable beings in creation; possesses the power of 'a million exploding suns' accompanied by his terrifying shadow persona, The Void.",
      mcuRole: "Introduced as 'Bob' in Thunderbolts*; his godlike molecular and energy manipulation make him a critical wild card when cosmic incursion forces arrive.",
      threatLevel: "Omega Cosmic",
      essentialAppearances: ["Thunderbolts*"]
    },
    {
      id: "wolverine",
      name: "Logan (Wolverine)",
      actor: "Hugh Jackman",
      universe: "Earth-10005 / The Void Survivor",
      affiliation: "X-Men / Deadpool's Partner",
      status: "Active in Earth-10005 timeline",
      avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Indestructible adamantium skeleton, relentless healing factor, veteran of Battleworld wars.",
      mcuRole: "Teamed with Wade Wilson to save Earth-10005 from TVA pruning; stands ready to protect mutantkind as realities collide.",
      threatLevel: "Omega Combatant",
      essentialAppearances: ["X-Men", "X2", "X-Men: Days of Future Past", "Logan", "Deadpool & Wolverine"]
    },
    {
      id: "thor",
      name: "Thor Odinson",
      actor: "Chris Hemsworth",
      universe: "Earth-616",
      affiliation: "Avengers / Asgard",
      status: "Cosmic Protector with Love",
      avatar: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Joined the Thor Corps — the interdimensional police force enforcing the divine will of God Emperor Doom on Battleworld.",
      mcuRole: "One of the original Trinity Avengers surviving the Infinity Saga; his lightning and cosmic divinity will be key against Latverian sorcery.",
      threatLevel: "Alpha Deity",
      essentialAppearances: ["Thor", "The Avengers", "Thor: Ragnarok", "Avengers: Infinity War", "Avengers: Endgame", "Thor: Love and Thunder"]
    },
    {
      id: "yelena-belova",
      name: "Yelena Belova",
      actor: "Florence Pugh",
      universe: "Earth-616",
      affiliation: "Thunderbolts*",
      status: "Field Leader of Thunderbolts*",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      comicHistory: "Elite Red Room assassin who succeeded Natasha Romanoff and led specialized strike teams.",
      mcuRole: "Field commander of the Thunderbolts*; ground-level tactical specialist in uncovering global conspiracies.",
      threatLevel: "Elite Black Ops",
      essentialAppearances: ["Black Widow", "Thunderbolts*"]
    }
  ],

  // Secret Wars Comic Lore Breakdown
  lore: {
    secretWars1984: {
      title: "Secret Wars (1984) - The First Battleworld",
      summary: "Created by Jim Shooter and Mike Zeck. The cosmic Beyonder transports Marvel's greatest heroes and villains to a patchwork planet constructed from pieces of destroyed worlds named Battleworld, instructing them: 'Slay your enemies and all that you desire shall be yours.'",
      doomTriumph: "Doctor Doom refused to be a pawn in the Beyonder's games. Utilizing stolen Galactus tech and advanced sorcery, Doom drained Galactus' power and then stole the omnipotent power of the Beyonder himself, becoming an all-powerful god."
    },
    secretWars2015: {
      title: "Secret Wars (2015) - God Emperor Doom & Incursions",
      summary: "Written by Jonathan Hickman and drawn by Esad Ribić. The multiverse suffered from a structural decay known as Incursions — the contraction of the multiverse causing two Earths to collide at universal coordinate points. When the final incursion occurred between Earth-616 (Main Marvel) and Earth-1610 (Ultimate Universe), all universes were destroyed.",
      godEmperorDoom: "Alongside Doctor Strange and the Molecule Man (Owen Reece), Victor Von Doom intercepted the omnipotent Beyonders. Doom absorbed their cosmic reality-warping energy and salvaged remnants of fragmented realities into a single surviving realm: Battleworld. Doom crowned himself God Emperor Doom, with Doctor Strange as his High Sheriff and a legion of Thors as his Thor Corps peacekeepers.",
      theResolution: "Reed Richards (Mister Fantastic) survived inside a dimensional Life Raft. When Reed confronted Doom on the peak of Castle Doom, Doom admitted: 'I believe Richards could have done it better.' Owen Reece transferred the godlike power to Reed Richards, who, alongside Franklin Richards and the Future Foundation, resurrected the entire Marvel Multiverse."
    },
    incursionsConcept: {
      title: "What is an Incursion in the MCU?",
      definition: "An incursion is a catastrophic multiversal phenomenon where the boundary between two universes deteriorates, causing their respective Earths to collide. The collision destroys both universes entirely, erasing trillions of lives across both dimensions.",
      mcuTriggers: "Introduced in Doctor Strange in the Multiverse of Madness and Loki. Incursions are triggered by excessive multiversal travel, Dreamwalking, memory manipulation, and timeline branching. Doctor Strange, Scarlet Witch, and the Fantastic Four's dimensional crossings have brought Earth-616 to the brink of the final incursion with Earth-10005 (Mutants) and retro-Earth."
    }
  },

  // Achievement Badges System
  badges: [
    {
      id: "first-blood",
      title: "FIRST STEP",
      description: "Mark your first title as watched.",
      category: "Core",
      icon: "play-circle",
      condition: (state) => state.watchedIds.length >= 1
    },
    {
      id: "the-short-road",
      title: "DOOM EXPRESS",
      description: "Complete all 10 direct narrative milestones on the Road to Doom.",
      category: "Core",
      icon: "flame",
      condition: (state) => {
        return window.DOOM_DATA.shortRoadIds.every(id => state.watchedIds.includes(id));
      }
    },
    {
      id: "god-of-stories",
      title: "GOD OF STORIES",
      description: "Watch both seasons of Loki to witness the weaving of Yggdrasil.",
      category: "Core",
      icon: "tree-pine",
      condition: (state) => {
        return state.watchedIds.includes("loki-season-1-2021") && state.watchedIds.includes("loki-season-2-2023");
      }
    },
    {
      id: "multiverse-scholar",
      title: "INCURSION SURVIVOR",
      description: "Watch No Way Home, Multiverse of Madness, and Deadpool & Wolverine.",
      category: "Core",
      icon: "infinity",
      condition: (state) => {
        return state.watchedIds.includes("spider-man-no-way-home-2021") &&
               state.watchedIds.includes("doctor-strange-multiverse-madness-2022") &&
               state.watchedIds.includes("deadpool-and-wolverine-2024");
      }
    },
    {
      id: "the-snap",
      title: "THE INFINITY SAGA",
      description: "Watch the complete Infinity Saga (Phases 1-3).",
      category: "Collector",
      icon: "sparkles",
      condition: (state, items) => {
        const infIds = items.filter(i => i.saga === "Infinity Saga").map(i => i.id);
        return infIds.length > 0 && infIds.every(id => state.watchedIds.includes(id));
      }
    },
    {
      id: "mutant-heritage",
      title: "CHILDREN OF THE ATOM",
      description: "Watch all Fox X-Men legacy titles in the collection.",
      category: "Collector",
      icon: "dna",
      condition: (state, items) => {
        const xmenIds = items.filter(i => i.universe === "xmen").map(i => i.id);
        return xmenIds.length > 0 && xmenIds.every(id => state.watchedIds.includes(id));
      }
    },
    {
      id: "ten-titles",
      title: "CINEMA CENTURION",
      description: "Watch at least 15 titles in the catalog.",
      category: "Collector",
      icon: "film",
      condition: (state) => state.watchedIds.length >= 15
    },
    {
      id: "kneel-before-doom",
      title: "KNEEL BEFORE DOOM",
      description: "Secret Easter Egg: Click the Doom Mask 5 times.",
      category: "Secret",
      icon: "crown",
      condition: (state) => (state.doomClicks || 0) >= 5
    },
    {
      id: "the-full-road",
      title: "BATTLEWORLD SOVEREIGN",
      description: "Watch every released title in the curated roadmap.",
      category: "Collector",
      icon: "trophy",
      condition: (state, items) => {
        const now = new Date();
        const releasedItems = items.filter(i => new Date(i.releaseDate) <= now);
        return releasedItems.length > 0 && releasedItems.every(id => state.watchedIds.includes(id.id));
      }
    }
  ]
};
